### ISSUE TITLE
Actifit didn't run in my android and display wrong message.

### ISSUE THREAD

**Issue by nawab69** [actifit/actifit#13]
## Bug

When I try to run Actifit app, It gives a error message that my phone is rooted & Actifit only run in non rooted device.
But my phone is non rooted device. I have checked the root status.  It shows that my phone is non rooted.

## Screenshot

![screenshot_20190202-235211](https://user-images.githubusercontent.com/44573643/52167749-0d8e3f00-274a-11e9-9662-6be32226517b.png)

![screenshot_20190202-235338](https://user-images.githubusercontent.com/44573643/52167752-197a0100-274a-11e9-831f-02b86c2ee9d8.png)

#### There is a same problem of another users. I have found it from google play store's user review.

![screenshot_20190203-001918](https://user-images.githubusercontent.com/44573643/52167764-5514cb00-274a-11e9-96da-59c9643e4006.png)

### My device:

Brand : LAVA
Model: IRIS 820
RAM: 1GB
ROM: 8GB
ROOT STATUS : NOT ROOTED

**Comment by mcfarhat** [comment]
Thank you for the report.

Actifit detects several risk factors relating to a device being rooted, including the device having high risk software installed. 

It is best to check if your device has any tool relating to rooting devices or performing any potentially malicious activity.

**Comment by nawab69** [comment]
Sir. I have checked all my apps properly. I have found nothing which is related to rooting device or performing any potentially malicious activity.

I have also restore and reset my device, format memory card.  But the problem still remain.
